version: '3.8'

services:
  app:
    image: rfqma/rfqma-v2:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3000"
    restart: always